services:
  api:
    build:
      context: API-Gateway
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=japierdole
      - DB_NAME=mvpdiploma
    ports:
      - "5001:5001"
    networks:
      - default
    depends_on:
      - db

  database_service:
    container_name: database-service-container
    build:
      context: ./database-service
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=japierdole
      - DB_NAME=mvpdiploma
      - SECRET_KEY=YAKNOW
    depends_on:
      - db
    ports:
      - "5002:5002"

  text_to_sql_service:
    container_name: text_to_sql_service-container
    build:
      context: ./text-to-sql-service
      dockerfile: Dockerfile
    environment:
      - API_HOST=api
      - API_PORT=5001
    ports:
      - "5003:5003"
    depends_on:
      - api

  diploma_frontend:
    build:
      context: ./diploma-frontend
      dockerfile: Dockerfile
    ports:
      - "5005:5173"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://diploma-text-to-sql-api-1:5173

  load-balancer:
    build:
      context: ReverseProxy
      dockerfile: Dockerfile
    ports:
      - "8810:8810"
    depends_on:
      - api
      - database_service
      - diploma_frontend
      - text_to_sql_service

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mvpdiploma
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=japierdole
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
